### ISSUE TITLE
Hex with odd digit count panics in modern compiler

### ISSUE THREAD

**Issue by richardkiss** [Chia-Network/clvm_tools_rs#93]
```
% run '(mod X (include *standard-cl-23*) (logand 0xf 100))'
thread '<unnamed>' panicked at src/compiler/sexp.rs:278:35:
should convert from hex: InvalidInputLength
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/kiss/unbacked/tmp/virtualenvs/_Users_kiss_projects_chia_chialisp_stdlib_main/venv/bin/run", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/Users/kiss/unbacked/tmp/virtualenvs/_Users_kiss_projects_chia_chialisp_stdlib_main/venv/lib/python3.12/site-packages/clvm_tools/cmds.py", line 101, in run
    sys.stdout.write(bytes(clvm_tools_rs.launch_tool("run", args, 2)).decode('utf8'))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: should convert from hex: InvalidInputLength
```

Probably better to just prefix 0-pad`0xf` to `0x0f`.

**Comment by prozacchiwawa** [comment]
thanks this is next in line: https://github.com/Chia-Network/clvm_tools_rs/pull/101
apologies for not having retired this issue earlier

**Comment by prozacchiwawa** [comment]
this has been fixed.
